[package]
name = "rsdsl_netlinkd"
version = "0.7.0-dev"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitfield = "0.14.0"
futures = "0.3.28"
futures-util = "0.3.27"
ipnet = "2.8.0"
libc = "0.2.149"
netlink-packet-route = "0.17.0"
notify = "5.1.0"
rsdsl_ip_config = { git = "https://github.com/rsdsl/ip_config.git", version = "0.2.2" }
rsdsl_pd_config = { git = "https://github.com/rsdsl/pd_config.git", version = "0.1.0" }
rtnetlink = "0.13.1"
serde_json = "1.0"
thiserror = "1.0"
tokio = { version = "1.26.0", features = ["rt-multi-thread"] }
