[package]
name = "rsdsl_netlinkd"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures-util = "0.3.27"
rtnetlink = "0.12.0"
thiserror = "1.0"
tokio = { version = "1.26.0", features = ["rt", "rt-multi-thread"] }
