[package]
name = "rsdsl_netlinkd_sys"
version = "0.4.8"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"

[build-dependencies]
bindgen = "0.66.1"
cc = "1.0.81"
